<?php
// /sitemap.xml — v3.0
// Apache rewrites /sitemap.xml → /sitemap.xml.php (see .htaccess). The actual
// XML is generated by the API so we don't duplicate the DB lookup.
require __DIR__ . '/api/bootstrap.php';
require __DIR__ . '/api/routes/public.php';
route_public_sitemap($CONFIG);
